# Generated by Django 5.0.4 on 2024-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_inserirfalta_ano_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inserirfalta',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
    ]
